import cv2
import numpy as np
import pandas as pd
from pathlib import Path
from scipy.optimize import linear_sum_assignment
from afis import MindtctExtractor


# ============================================================
# PATHS
# ============================================================

CLEAN_ROOT = Path("data/split/test")
DISTORTED_ROOT = Path("data/rectification_test/distorted")
# Kept separate from the legacy rectification output generated by the older
# FingerprintRectificationNet. Final analysis must use the frozen DDRNet_DIR
# checkpoint outputs that are evaluated by evaluate_matching_rectification.py.
RECTIFIED_ROOT = Path("data/rectified_ddrnet_test")

OUTPUT_DIR = Path("experiments/minutiae_rectification")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_CSV = OUTPUT_DIR / "minutiae_comparison.csv"


DISTORTION_TYPES = ["elastic", "local", "bending"]


# ============================================================
# IMAGE LOADING
# ============================================================

def load_image(path):
    image = cv2.imread(
        str(path),
        cv2.IMREAD_GRAYSCALE
    )

    if image is None:
        raise RuntimeError(
            f"Could not read image: {path}"
        )

    return image


# ============================================================
# MINDTCT
# ============================================================

def extract_minutiae(path, extractor):

    image = load_image(path)

    template = extractor.extract_minutiae(image)

    # Format:
    # [x, y, angle, type, quality]
    minutiae = np.asarray(
        template.minutiae,
        dtype=np.float32
    )

    return minutiae


# ============================================================
# BASIC MINUTIAE STATISTICS
# ============================================================

def minutiae_stats(minutiae):

    if len(minutiae) == 0:

        return {
            "count": 0,
            "quality": np.nan,
            "endings": 0,
            "bifurcations": 0
        }

    types = minutiae[:, 3]
    qualities = minutiae[:, 4]

    endings = int(
        np.sum(types == 0)
    )

    bifurcations = int(
        np.sum(types == 1)
    )

    return {
        "count": len(minutiae),

        "quality": float(
            np.mean(qualities)
        ),

        "endings": endings,

        "bifurcations": bifurcations
    }


# ============================================================
# MINUTIAE CORRESPONDENCE
# ============================================================

def match_minutiae(
    reference,
    candidate,
    distance_threshold=15.0
):
    """
    Match candidate minutiae to reference minutiae
    using Hungarian assignment.

    Only pairs within distance_threshold are accepted.

    Matching uses:
        - spatial distance
        - minutia type

    Orientation is not used for this diagnostic metric.
    """

    if len(reference) == 0 or len(candidate) == 0:

        return {
            "matched": 0,
            "reference_count": len(reference),
            "candidate_count": len(candidate),
            "match_rate": 0.0,
            "mean_distance": np.nan,
            "median_distance": np.nan
        }

    ref_xy = reference[:, :2]
    cand_xy = candidate[:, :2]

    ref_type = reference[:, 3].astype(int)
    cand_type = candidate[:, 3].astype(int)

    # --------------------------------------------------------
    # Distance matrix
    # --------------------------------------------------------

    diff = (
        ref_xy[:, None, :]
        - cand_xy[None, :, :]
    )

    distance = np.sqrt(
        np.sum(
            diff ** 2,
            axis=2
        )
    )

    # --------------------------------------------------------
    # Prevent different minutia types from matching
    # --------------------------------------------------------

    type_mismatch = (
        ref_type[:, None]
        != cand_type[None, :]
    )

    cost = distance.copy()

    # Large penalty for different types
    cost[type_mismatch] = 100000.0

    # --------------------------------------------------------
    # Hungarian assignment
    # --------------------------------------------------------

    rows, cols = linear_sum_assignment(cost)

    valid_distances = []

    for r, c in zip(rows, cols):

        d = distance[r, c]

        if (
            d <= distance_threshold
            and ref_type[r] == cand_type[c]
        ):
            valid_distances.append(float(d))

    matched = len(valid_distances)

    match_rate = (
        matched / len(reference)
        if len(reference) > 0
        else 0.0
    )

    if valid_distances:

        mean_distance = float(
            np.mean(valid_distances)
        )

        median_distance = float(
            np.median(valid_distances)
        )

    else:

        mean_distance = np.nan
        median_distance = np.nan

    return {
        "matched": matched,
        "reference_count": len(reference),
        "candidate_count": len(candidate),
        "match_rate": match_rate,
        "mean_distance": mean_distance,
        "median_distance": median_distance
    }


# ============================================================
# PATH CONVERSION
# ============================================================

def transformed_path(
    clean_path,
    root,
    distortion_type
):

    family = clean_path.parent.parent.name
    member = clean_path.parent.name
    filename = clean_path.stem

    name = (
        f"{family}__{member}__"
        f"{filename}__{distortion_type}.png"
    )

    return root / name


# ============================================================
# COLLECT CLEAN IMAGES
# ============================================================

def collect_clean_images():

    images = []

    for family_dir in sorted(
        CLEAN_ROOT.glob("FAMILY-*")
    ):

        if not family_dir.is_dir():
            continue

        for member_dir in sorted(
            family_dir.iterdir()
        ):

            if not member_dir.is_dir():
                continue

            images.extend(
                sorted(
                    member_dir.glob("*.png")
                )
            )

    return images


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 90)
    print("CORRECTED MINUTIAE PRESERVATION ANALYSIS")
    print("=" * 90)

    extractor = MindtctExtractor()

    clean_images = collect_clean_images()

    print(
        f"\nClean test images: "
        f"{len(clean_images)}"
    )

    if len(clean_images) != 225:

        raise RuntimeError(
            f"Expected 225 images, "
            f"found {len(clean_images)}"
        )

    results = []

    # ========================================================
    # DISTORTION TYPES
    # ========================================================

    for distortion_type in DISTORTION_TYPES:

        print("\n" + "=" * 90)
        print(
            f"ANALYZING: "
            f"{distortion_type.upper()}"
        )
        print("=" * 90)

        for idx, clean_path in enumerate(
            clean_images,
            start=1
        ):

            distorted_path = transformed_path(
                clean_path,
                DISTORTED_ROOT,
                distortion_type
            )

            rectified_path = transformed_path(
                clean_path,
                RECTIFIED_ROOT,
                distortion_type
            )

            if not distorted_path.exists():

                raise FileNotFoundError(
                    distorted_path
                )

            if not rectified_path.exists():

                raise FileNotFoundError(
                    rectified_path
                )

            # ------------------------------------------------
            # Extract minutiae
            # ------------------------------------------------

            clean = extract_minutiae(
                clean_path,
                extractor
            )

            distorted = extract_minutiae(
                distorted_path,
                extractor
            )

            rectified = extract_minutiae(
                rectified_path,
                extractor
            )

            # ------------------------------------------------
            # Statistics
            # ------------------------------------------------

            clean_s = minutiae_stats(clean)
            distorted_s = minutiae_stats(
                distorted
            )
            rectified_s = minutiae_stats(
                rectified
            )

            # ------------------------------------------------
            # Distorted vs clean
            # ------------------------------------------------

            distorted_match = match_minutiae(
                clean,
                distorted
            )

            # ------------------------------------------------
            # Rectified vs clean
            # ------------------------------------------------

            rectified_match = match_minutiae(
                clean,
                rectified
            )

            # ------------------------------------------------
            # Save
            # ------------------------------------------------

            results.append({

                "family":
                    clean_path.parent.parent.name,

                "member":
                    clean_path.parent.name,

                "image":
                    clean_path.name,

                "distortion_type":
                    distortion_type,

                # Counts
                "clean_count":
                    clean_s["count"],

                "distorted_count":
                    distorted_s["count"],

                "rectified_count":
                    rectified_s["count"],

                # Quality
                "clean_quality":
                    clean_s["quality"],

                "distorted_quality":
                    distorted_s["quality"],

                "rectified_quality":
                    rectified_s["quality"],

                # Types
                "clean_endings":
                    clean_s["endings"],

                "distorted_endings":
                    distorted_s["endings"],

                "rectified_endings":
                    rectified_s["endings"],

                "clean_bifurcations":
                    clean_s["bifurcations"],

                "distorted_bifurcations":
                    distorted_s["bifurcations"],

                "rectified_bifurcations":
                    rectified_s["bifurcations"],

                # Correspondence
                "distorted_matched":
                    distorted_match["matched"],

                "rectified_matched":
                    rectified_match["matched"],

                "distorted_match_rate":
                    distorted_match["match_rate"],

                "rectified_match_rate":
                    rectified_match["match_rate"],

                "distorted_mean_distance":
                    distorted_match["mean_distance"],

                "rectified_mean_distance":
                    rectified_match["mean_distance"],

                "distorted_median_distance":
                    distorted_match["median_distance"],

                "rectified_median_distance":
                    rectified_match["median_distance"],
            })

            if (
                idx % 25 == 0
                or idx == len(clean_images)
            ):

                print(
                    f"  Processed: "
                    f"{idx}/{len(clean_images)}"
                )

    # ========================================================
    # SAVE CSV
    # ========================================================

    df = pd.DataFrame(results)

    df.to_csv(
        OUTPUT_CSV,
        index=False
    )

    # ========================================================
    # SUMMARY
    # ========================================================

    print("\n")
    print("=" * 100)
    print("CORRECTED MINUTIAE PRESERVATION SUMMARY")
    print("=" * 100)

    for distortion_type in DISTORTION_TYPES:

        subset = df[
            df["distortion_type"]
            == distortion_type
        ]

        print(
            f"\n{distortion_type.upper()}"
        )

        # ----------------------------------------------------
        # Count
        # ----------------------------------------------------

        print("\n  Mean minutiae count:")

        print(
            f"    Clean:     "
            f"{subset['clean_count'].mean():.2f}"
        )

        print(
            f"    Distorted: "
            f"{subset['distorted_count'].mean():.2f}"
        )

        print(
            f"    Rectified: "
            f"{subset['rectified_count'].mean():.2f}"
        )

        # ----------------------------------------------------
        # Quality
        # ----------------------------------------------------

        print("\n  Mean minutiae quality:")

        print(
            f"    Clean:     "
            f"{subset['clean_quality'].mean():.4f}"
        )

        print(
            f"    Distorted: "
            f"{subset['distorted_quality'].mean():.4f}"
        )

        print(
            f"    Rectified: "
            f"{subset['rectified_quality'].mean():.4f}"
        )

        # ----------------------------------------------------
        # Types
        # ----------------------------------------------------

        print("\n  Mean ridge endings:")

        print(
            f"    Clean:     "
            f"{subset['clean_endings'].mean():.2f}"
        )

        print(
            f"    Distorted: "
            f"{subset['distorted_endings'].mean():.2f}"
        )

        print(
            f"    Rectified: "
            f"{subset['rectified_endings'].mean():.2f}"
        )

        print("\n  Mean bifurcations:")

        print(
            f"    Clean:     "
            f"{subset['clean_bifurcations'].mean():.2f}"
        )

        print(
            f"    Distorted: "
            f"{subset['distorted_bifurcations'].mean():.2f}"
        )

        print(
            f"    Rectified: "
            f"{subset['rectified_bifurcations'].mean():.2f}"
        )

        # ----------------------------------------------------
        # Spatial correspondence
        # ----------------------------------------------------

        print(
            "\n  Minutiae correspondence "
            "(reference = CLEAN):"
        )

        print(
            f"    Distorted matched: "
            f"{subset['distorted_matched'].mean():.2f}"
        )

        print(
            f"    Rectified matched: "
            f"{subset['rectified_matched'].mean():.2f}"
        )

        print(
            f"    Distorted match rate: "
            f"{subset['distorted_match_rate'].mean():.4f}"
        )

        print(
            f"    Rectified match rate: "
            f"{subset['rectified_match_rate'].mean():.4f}"
        )

        print(
            f"    Distorted mean distance: "
            f"{subset['distorted_mean_distance'].mean():.2f} px"
        )

        print(
            f"    Rectified mean distance: "
            f"{subset['rectified_mean_distance'].mean():.2f} px"
        )

        # ----------------------------------------------------
        # Improvement
        # ----------------------------------------------------

        d_rate = subset[
            "distorted_match_rate"
        ].mean()

        r_rate = subset[
            "rectified_match_rate"
        ].mean()

        if d_rate > 0:

            rate_change = (
                (r_rate - d_rate)
                / d_rate
                * 100
            )

            print(
                f"    Match-rate change: "
                f"{rate_change:+.2f}%"
            )

        d_dist = subset[
            "distorted_mean_distance"
        ].mean()

        r_dist = subset[
            "rectified_mean_distance"
        ].mean()

        if (
            np.isfinite(d_dist)
            and np.isfinite(r_dist)
            and d_dist > 0
        ):

            distance_change = (
                (d_dist - r_dist)
                / d_dist
                * 100
            )

            print(
                f"    Distance improvement: "
                f"{distance_change:+.2f}%"
            )

    # ========================================================
    # OVERALL
    # ========================================================

    print("\n" + "=" * 100)
    print("OVERALL")
    print("=" * 100)

    print(
        f"\nMean minutiae count:"
    )

    print(
        f"  Clean:     "
        f"{df['clean_count'].mean():.2f}"
    )

    print(
        f"  Distorted: "
        f"{df['distorted_count'].mean():.2f}"
    )

    print(
        f"  Rectified: "
        f"{df['rectified_count'].mean():.2f}"
    )

    print(
        "\nMean minutiae quality:"
    )

    print(
        f"  Clean:     "
        f"{df['clean_quality'].mean():.4f}"
    )

    print(
        f"  Distorted: "
        f"{df['distorted_quality'].mean():.4f}"
    )

    print(
        f"  Rectified: "
        f"{df['rectified_quality'].mean():.4f}"
    )

    print(
        "\nMinutiae correspondence:"
    )

    print(
        f"  Distorted matched: "
        f"{df['distorted_matched'].mean():.2f}"
    )

    print(
        f"  Rectified matched: "
        f"{df['rectified_matched'].mean():.2f}"
    )

    print(
        f"  Distorted match rate: "
        f"{df['distorted_match_rate'].mean():.4f}"
    )

    print(
        f"  Rectified match rate: "
        f"{df['rectified_match_rate'].mean():.4f}"
    )

    print(
        f"  Distorted mean distance: "
        f"{df['distorted_mean_distance'].mean():.2f} px"
    )

    print(
        f"  Rectified mean distance: "
        f"{df['rectified_mean_distance'].mean():.2f} px"
    )

    print("\n" + "=" * 100)

    print(
        f"Results saved to:\n"
        f"{OUTPUT_CSV}"
    )

    print("=" * 100)


if __name__ == "__main__":
    main()
